/* LoginPage */
export const LOGIN_PAGE_SHOW_LOGIN_FORM = 'LOGIN_PAGE_SHOW_LOGIN_FORM';
export const RESET_LOGIN_PAGE = 'RESET_LOGIN_PAGE';
export const RESET_LOCAL_STORAGE = 'RESET_LOCAL_STORAGE';
export const RESET_LOGIN_PAGE_META = 'RESET_LOGIN_PAGE_META';
export const UPDATE_LOGIN_PAGE_FORM_FIELD = 'UPDATE_LOGIN_PAGE_FORM_FIELD';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// Entity List Page
export const GET_ENTITY_LIST_REQUEST = 'GET_ENTITY_LIST_REQUEST';
export const GET_ENTITY_LIST_SUCCESS = 'GET_ENTITY_LIST_SUCCESS';
export const GET_ENTITY_LIST_ERROR = 'GET_ENTITY_LIST_ERROR';

export const RESET_ENTITY_LIST_META = 'RESET_ENTITY_LIST_META';
export const RESET_ENTITY_LIST_PAGE = 'RESET_ENTITY_LIST_PAGE';

// Entity Basic Page
export const GET_ENTITY_BY_ID_REQUEST = 'GET_ENTITY_BY_ID_REQUEST';
export const GET_ENTITY_BY_ID_SUCCESS = 'GET_ENTITY_BY_ID_SUCCESS';
export const GET_ENTITY_BY_ID_ERROR = 'GET_ENTITY_BY_ID_ERROR';

export const SUBMIT_ENTITY_REQUEST = 'SUBMIT_ENTITY_REQUEST';
export const SUBMIT_ENTITY_SUCCESS = 'SUBMIT_ENTITY_SUCCESS';
export const SUBMIT_ENTITY_ERROR = 'SUBMIT_ENTITY_ERROR';

export const DELETE_ENTITY_BY_ID_REQUEST = 'DELETE_ENTITY_BY_ID_REQUEST';
export const DELETE_ENTITY_BY_ID_SUCCESS = 'DELETE_ENTITY_BY_ID_SUCCESS';
export const DELETE_ENTITY_BY_ID_ERROR = 'DELETE_ENTITY_BY_ID_ERROR';

export const SUSPEND_ENTITY_BY_ID_REQUEST = 'SUSPEND_ENTITY_BY_ID_REQUEST';
export const SUSPEND_ENTITY_BY_ID_SUCCESS = 'SUSPEND_ENTITY_BY_ID_SUCCESS';
export const SUSPEND_ENTITY_BY_ID_ERROR = 'SUSPEND_ENTITY_BY_ID_ERROR';

export const UNSUSPEND_ENTITY_BY_ID_REQUEST = 'UNSUSPEND_ENTITY_BY_ID_REQUEST';
export const UNSUSPEND_ENTITY_BY_ID_SUCCESS = 'UNSUSPEND_ENTITY_BY_ID_SUCCESS';
export const UNSUSPEND_ENTITY_BY_ID_ERROR = 'UNSUSPEND_ENTITY_BY_ID_ERROR';

export const GET_ENTITY_LOCATION_LIST_REQUEST = 'GET_ENTITY_LOCATION_LIST_REQUEST';
export const GET_ENTITY_LOCATION_LIST_SUCCESS = 'GET_ENTITY_LOCATION_LIST_SUCCESS';
export const GET_ENTITY_LOCATION_LIST_ERROR = 'GET_ENTITY_LOCATION_LIST_ERROR';

export const RESET_ENTITY_DETAIL_META = 'RESET_ENTITY_DETAIL_META';
export const RESET_ENTITY_DETAIL_PAGE = 'RESET_ENTITY_DETAIL_PAGE';

// USER LIST

export const GET_USER_LIST_REQUEST = 'GET_USER_LIST_REQUEST';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_ERROR = 'GET_USER_LIST_ERROR';

export const RESET_USER_LIST_META = 'RESET_USER_LIST_META';
export const RESET_USER_LIST_PAGE = 'RESET_USER_LIST_PAGE';

// USER BASIC PAGE

export const GET_GROUPS_FOR_USER_REQUEST = 'GET_GROUPS_FOR_USER_REQUEST';
export const GET_GROUPS_FOR_USER_SUCCESS = 'GET_GROUPS_FOR_USER_SUCCESS';
export const GET_GROUPS_FOR_USER_ERROR = 'GET_GROUPS_FOR_USER_ERROR';

export const GET_DOORS_FOR_USER_REQUEST = 'GET_DOORS_FOR_USER_REQUEST';
export const GET_DOORS_FOR_USER_SUCCESS = 'GET_DOORS_FOR_USER_SUCCESS';
export const GET_DOORS_FOR_USER_ERROR = 'GET_DOORS_FOR_USER_ERROR';

export const GET_USER_BASIC_REQUEST = 'GET_USER_BASIC_REQUEST';
export const GET_USER_BASIC_SUCCESS = 'GET_USER_BASIC_SUCCESS';
export const GET_USER_BASIC_ERROR = 'GET_USER_BASIC_ERROR';

export const SUBMIT_USER_BASIC_REQUEST = 'SUBMIT_USER_BASIC_REQUEST';
export const SUBMIT_USER_BASIC_SUCCESS = 'SUBMIT_USER_BASIC_SUCCESS';
export const SUBMIT_USER_BASIC_ERROR = 'SUBMIT_USER_BASIC_ERROR';

export const DELETE_USER_BASIC_REQUEST = 'DELETE_USER_BASIC_REQUEST';
export const DELETE_USER_BASIC_SUCCESS = 'DELETE_USER_BASIC_SUCCESS';
export const DELETE_USER_BASIC_ERROR = 'DELETE_USER_BASIC_ERROR';
export const SUSPEND_USER_BASIC_REQUEST = 'SUSPEND_USER_BASIC_REQUEST';
export const SUSPEND_USER_BASIC_SUCCESS = 'SUSPEND_USER_BASIC_SUCCESS';
export const SUSPEND_USER_BASIC_ERROR = 'SUSPEND_USER_BASIC_ERROR';

export const UNSUSPEND_USER_BASIC_REQUEST = 'UNSUSPEND_USER_BASIC_REQUEST';
export const UNSUSPEND_USER_BASIC_SUCCESS = 'UNSUSPEND_USER_BASIC_SUCCESS';
export const UNSUSPEND_USER_BASIC_ERROR = 'UNSUSPEND_USER_BASIC_ERROR';

export const RESET_USER_BASIC_META = 'RESET_USER_BASIC_META';
export const RESET_USER_BASIC_PAGE = 'RESET_USER_BASIC_PAGE';

// User Authentications Tab
export const GET_USER_AUTHENTICATIONS_REQUEST = 'GET_USER_AUTHENTICATIONS_REQUEST';
export const GET_USER_AUTHENTICATIONS_SUCCESS = 'GET_USER_AUTHENTICATIONS_SUCCESS';
export const GET_USER_AUTHENTICATIONS_ERROR = 'GET_USER_AUTHENTICATIONS_ERROR';

export const SUBMIT_USER_AUTHENTICATION_REQUEST = 'SUBMIT_USER_AUTHENTICATION_REQUEST';
export const SUBMIT_USER_AUTHENTICATION_SUCCESS = 'SUBMIT_USER_AUTHENTICATION_SUCCESS';
export const SUBMIT_USER_AUTHENTICATION_ERROR = 'SUBMIT_USER_AUTHENTICATION_ERROR';

export const DELETE_USER_AUTHENTICATION_REQUEST = 'DELETE_USER_AUTHENTICATION_REQUEST';
export const DELETE_USER_AUTHENTICATION_SUCCESS = 'DELETE_USER_AUTHENTICATION_SUCCESS';
export const DELETE_USER_AUTHENTICATION_ERROR = 'DELETE_USER_AUTHENTICATION_ERROR';

export const GET_CUSTOM_AUTHENTICATIONS_REQUEST = 'GET_CUSTOM_AUTHENTICATIONS_REQUEST';
export const GET_CUSTOM_AUTHENTICATIONS_SUCCESS = 'GET_CUSTOM_AUTHENTICATIONS_SUCCESS';
export const GET_CUSTOM_AUTHENTICATIONS_ERROR = 'GET_CUSTOM_AUTHENTICATIONS_ERROR';

export const SUSPEND_USER_AUTHENTICATION_REQUEST = 'SUSPEND_USER_AUTHENTICATION_REQUEST';
export const SUSPEND_USER_AUTHENTICATION_SUCCESS = 'SUSPEND_USER_AUTHENTICATION_SUCCESS';
export const SUSPEND_USER_AUTHENTICATION_ERROR = 'SUSPEND_USER_AUTHENTICATION_ERROR';

export const UNSUSPEND_USER_AUTHENTICATION_REQUEST = 'UNSUSPEND_USER_AUTHENTICATION_REQUEST';
export const UNSUSPEND_USER_AUTHENTICATION_SUCCESS = 'UNSUSPEND_USER_AUTHENTICATION_SUCCESS';
export const UNSUSPEND_USER_AUTHENTICATION_ERROR = 'UNSUSPEND_USER_AUTHENTICATION_ERROR';

export const RESET_USER_AUTHENTICATION_META = 'RESET_USER_AUTHENTICATION_META';
export const RESET_USER_AUTHENTICATION_PAGE = 'RESET_USER_AUTHENTICATION_PAGE';

// User Permission History Tab
export const GET_USER_PERMISSION_HISTORY_LIST_REQUEST = 'GET_USER_PERMISSION_HISTORY_LIST_REQUEST';
export const GET_USER_PERMISSION_HISTORY_LIST_SUCCESS = 'GET_USER_PERMISSION_HISTORY_LIST_SUCCESS';
export const GET_USER_PERMISSION_HISTORY_LIST_ERROR = 'GET_USER_PERMISSION_HISTORY_LIST_ERROR';

export const GET_USER_PERMISSION_HISTORY_BY_ID_REQUEST = 'GET_USER_PERMISSION_HISTORY_BY_ID_REQUEST';
export const GET_USER_PERMISSION_HISTORY_BY_ID_SUCCESS = 'GET_USER_PERMISSION_HISTORY_BY_ID_SUCCESS';
export const GET_USER_PERMISSION_HISTORY_BY_ID_ERROR = 'GET_USER_PERMISSION_HISTORY_BY_ID_ERROR';

export const RESET_USER_PERMISSION_HISTORY_META = 'RESET_USER_PERMISSION_HISTORY_META';
export const RESET_USER_PERMISSION_HISTORY_PAGE = 'RESET_USER_PERMISSION_HISTORY_PAGE';

// User Access Rights
export const GET_USER_ACCESS_RIGHTS_LIST_REQUEST = 'GET_USER_ACCESS_RIGHTS_LIST_REQUEST';
export const GET_USER_ACCESS_RIGHTS_LIST_SUCCESS = 'GET_USER_ACCESS_RIGHTS_LIST_SUCCESS';
export const GET_USER_ACCESS_RIGHTS_LIST_ERROR = 'GET_USER_ACCESS_RIGHTS_LIST_ERROR';
export const RESET_USER_ACCESS_RIGHTS_META = 'RESET_USER_ACCESS_RIGHTS_META';
export const RESET_USER_ACCESS_RIGHTS_PAGE = 'RESET_USER_ACCESS_RIGHTS_PAGE';

// CONTROLLER LIST
export const GET_CONTROLLER_LIST_REQUEST = 'GET_CONTROLLER_LIST_REQUEST';
export const GET_CONTROLLER_LIST_SUCCESS = 'GET_CONTROLLER_LIST_SUCCESS';
export const GET_CONTROLLER_LIST_ERROR = 'GET_CONTROLLER_LIST_ERROR';

export const RESET_CONTROLLER_LIST_META = 'RESET_CONTROLLER_LIST_META';
export const RESET_CONTROLLER_LIST_PAGE = 'RESET_CONTROLLER_LIST_PAGE';

// CONTROLLER BASIC PAGE
export const GET_CONTROLLER_BASIC_REQUEST = 'GET_CONTROLLER_BASIC_REQUEST';
export const GET_CONTROLLER_BASIC_SUCCESS = 'GET_CONTROLLER_BASIC_SUCCESS';
export const GET_CONTROLLER_BASIC_ERROR = 'GET_CONTROLLER_BASIC_ERROR';

export const SUBMIT_CONTROLLER_BASIC_REQUEST = 'SUBMIT_CONTROLLER_BASIC_REQUEST';
export const SUBMIT_CONTROLLER_BASIC_SUCCESS = 'SUBMIT_CONTROLLER_BASIC_SUCCESS';
export const SUBMIT_CONTROLLER_BASIC_ERROR = 'SUBMIT_CONTROLLER_BASIC_ERROR';

export const DELETE_CONTROLLER_BASIC_REQUEST = 'DELETE_CONTROLLER_BASIC_REQUEST';
export const DELETE_CONTROLLER_BASIC_SUCCESS = 'DELETE_CONTROLLER_BASIC_SUCCESS';
export const DELETE_CONTROLLER_BASIC_ERROR = 'DELETE_CONTROLLER_BASIC_ERROR';

export const SUSPEND_CONTROLLER_BASIC_REQUEST = 'SUSPEND_CONTROLLER_BASIC_REQUEST';
export const SUSPEND_CONTROLLER_BASIC_SUCCESS = 'SUSPEND_CONTROLLER_BASIC_SUCCESS';
export const SUSPEND_CONTROLLER_BASIC_ERROR = 'SUSPEND_CONTROLLER_BASIC_ERROR';

export const UNSUSPEND_CONTROLLER_BASIC_REQUEST = 'UNSUSPEND_CONTROLLER_BASIC_REQUEST';
export const UNSUSPEND_CONTROLLER_BASIC_SUCCESS = 'UNSUSPEND_CONTROLLER_BASIC_SUCCESS';
export const UNSUSPEND_CONTROLLER_BASIC_ERROR = 'UNSUSPEND_CONTROLLER_BASIC_ERROR';

export const RESET_CONTROLLER_BASIC_META = 'RESET_CONTROLLER_BASIC_META';
export const RESET_CONTROLLER_BASIC_PAGE = 'RESET_CONTROLLER_BASIC_PAGE';

// CONTROLLER CONFIGURATION PAGE
export const SUBMIT_CONTROLLER_CONFIGURATION_REQUEST = 'SUBMIT_CONTROLLER_CONFIGURATION_REQUEST';
export const SUBMIT_CONTROLLER_CONFIGURATION_SUCCESS = 'SUBMIT_CONTROLLER_CONFIGURATION_SUCCESS';
export const SUBMIT_CONTROLLER_CONFIGURATION_ERROR = 'SUBMIT_CONTROLLER_CONFIGURATION_ERROR';

export const RESET_CONTROLLER_CONFIGURATION_META = 'RESET_CONTROLLER_CONFIGURATION_META';
export const RESET_CONTROLLER_CONFIGURATION_PAGE = 'RESET_CONTROLLER_CONFIGURATION_PAGE';

// Admin List
export const GET_ADMIN_LIST_REQUEST = 'GET_ADMIN_LIST_REQUEST';
export const GET_ADMIN_LIST_SUCCESS = 'GET_ADMIN_LIST_SUCCESS';
export const GET_ADMIN_LIST_ERROR = 'GET_ADMIN_LIST_ERROR';

export const RESET_ADMIN_LIST_META = 'RESET_ADMIN_LIST_META';
export const RESET_ADMIN_LIST_PAGE = 'RESET_ADMIN_LIST_PAGE';

// Admin Detail Page
export const GET_ADMIN_BY_ID_REQUEST = 'GET_ADMIN_BY_ID_REQUEST';
export const GET_ADMIN_BY_ID_SUCCESS = 'GET_ADMIN_BY_ID_SUCCESS';
export const GET_ADMIN_BY_ID_ERROR = 'GET_ADMIN_BY_ID_ERROR';

export const SUBMIT_ADMIN_REQUEST = 'SUBMIT_ADMIN_REQUEST';
export const SUBMIT_ADMIN_SUCCESS = 'SUBMIT_ADMIN_SUCCESS';
export const SUBMIT_ADMIN_ERROR = 'SUBMIT_ADMIN_ERROR';

export const SUSPEND_ADMIN_BY_ID_REQUEST = 'SUSPEND_ADMIN_BY_ID_REQUEST';
export const SUSPEND_ADMIN_BY_ID_SUCCESS = 'SUSPEND_ADMIN_BY_ID_SUCCESS';
export const SUSPEND_ADMIN_BY_ID_ERROR = 'SUSPEND_ADMIN_BY_ID_ERROR';

export const UNSUSPEND_ADMIN_BY_ID_REQUEST = 'UNSUSPEND_ADMIN_BY_ID_REQUEST';
export const UNSUSPEND_ADMIN_BY_ID_SUCCESS = 'UNSUSPEND_ADMIN_BY_ID_SUCCESS';
export const UNSUSPEND_ADMIN_BY_ID_ERROR = 'UNSUSPEND_ADMIN_BY_ID_ERROR';

export const UPDATE_ADMIN_PASSWORD_REQUEST = 'UPDATE_ADMIN_PASSWORD_REQUEST';
export const UPDATE_ADMIN_PASSWORD_SUCCESS = 'UPDATE_ADMIN_PASSWORD_SUCCESS';
export const UPDATE_ADMIN_PASSWORD_ERROR = 'UPDATE_ADMIN_PASSWORD_ERROR';

export const RESET_ADMIN_DETAIL_META = 'RESET_ADMIN_DETAIL_META';
export const RESET_ADMIN_DETAIL_PAGE = 'RESET_ADMIN_DETAIL_PAGE';

// Department List
export const GET_DEPARTMENT_LIST_REQUEST = 'GET_DEPARTMENT_LIST_REQUEST';
export const GET_DEPARTMENT_LIST_SUCCESS = 'GET_DEPARTMENT_LIST_SUCCESS';
export const GET_DEPARTMENT_LIST_ERROR = 'GET_DEPARTMENT_LIST_ERROR';

// Department Detail
export const GET_DEPARTMENT_BY_ID_REQUEST = 'GET_DEPARTMENT_BY_ID_REQUEST';
export const GET_DEPARTMENT_BY_ID_SUCCESS = 'GET_DEPARTMENT_BY_ID_SUCCESS';
export const GET_DEPARTMENT_BY_ID_ERROR = 'GET_DEPARTMENT_BY_ID_ERROR';
export const RESET_DEPARTMENT_DETAIL_PAGE = 'RESET_DEPARTMENT_DETAIL_PAGE';

// Access Rights User List

export const GET_ACCESS_RIGHTS_USER_LIST_REQUEST = 'GET_ACCESS_RIGHTS_USER_LIST_REQUEST';
export const GET_ACCESS_RIGHTS_USER_LIST_SUCCESS = 'GET_ACCESS_RIGHTS_USER_LIST_SUCCESS';
export const GET_ACCESS_RIGHTS_USER_LIST_ERROR = 'GET_ACCESS_RIGHTS_USER_LIST_ERROR';

export const GET_ACCESS_RIGHTS_USER_BY_ID_REQUEST = 'GET_ACCESS_RIGHTS_USER_BY_ID_REQUEST';
export const GET_ACCESS_RIGHTS_USER_BY_ID_SUCCESS = 'GET_ACCESS_RIGHTS_USER_BY_ID_SUCCESS';
export const GET_ACCESS_RIGHTS_USER_BY_ID_ERROR = 'GET_ACCESS_RIGHTS_USER_BY_ID_ERROR';

export const SUBMIT_ACCESS_RIGHTS_USER_REQUEST = 'SUBMIT_ACCESS_RIGHTS_USER_REQUEST';
export const SUBMIT_ACCESS_RIGHTS_USER_SUCCESS = 'SUBMIT_ACCESS_RIGHTS_USER_SUCCESS';
export const SUBMIT_ACCESS_RIGHTS_USER_ERROR = 'SUBMIT_ACCESS_RIGHTS_USER_ERROR';

export const DELETE_ACCESS_RIGHTS_USER_BY_ID_REQUEST = 'DELETE_ACCESS_RIGHTS_USER_BY_ID_REQUEST';
export const DELETE_ACCESS_RIGHTS_USER_BY_ID_SUCCESS = 'DELETE_ACCESS_RIGHTS_USER_BY_ID_SUCCESS';
export const DELETE_ACCESS_RIGHTS_USER_BY_ID_ERROR = 'DELETE_ACCESS_RIGHTS_USER_BY_ID_ERROR';

export const GET_USER_FROM_ACCESS_RIGHTS_REQUEST = 'GET_USER_FROM_ACCESS_RIGHTS_REQUEST';
export const GET_USER_FROM_ACCESS_RIGHTS_ERROR = 'GET_USER_FROM_ACCESS_RIGHTS_ERROR';
export const GET_USER_FROM_ACCESS_RIGHTS_SUCCESS = 'GET_USER_FROM_ACCESS_RIGHTS_SUCCESS';

export const SUSPEND_LOCATION_ACCESS_RIGHTS_BY_USER_REQUEST = 'SUSPEND_LOCATION_ACCESS_RIGHTS_BY_USER_REQUEST';
export const SUSPEND_LOCATION_ACCESS_RIGHTS_BY_USER_SUCCESS = 'SUSPEND_LOCATION_ACCESS_RIGHTS_BY_USER_SUCCESS';
export const SUSPEND_LOCATION_ACCESS_RIGHTS_BY_USER_ERROR = 'SUSPEND_LOCATION_ACCESS_RIGHTS_BY_USER_ERROR';

export const REACTIVATE_LOCATION_ACCESS_RIGHTS_BY_USER_REQUEST = 'REACTIVATE_LOCATION_ACCESS_RIGHTS_BY_USER_REQUEST';
export const REACTIVATE_LOCATION_ACCESS_RIGHTS_BY_USER_SUCCESS = 'REACTIVATE_LOCATION_ACCESS_RIGHTS_BY_USER_SUCCESS';
export const REACTIVATE_LOCATION_ACCESS_RIGHTS_BY_USER_ERROR = 'REACTIVATE_LOCATION_ACCESS_RIGHTS_BY_USER_ERROR';

export const RESET_ACCESS_RIGHTS_USER_META = 'RESET_ACCESS_RIGHTS_USER_META';
export const RESET_ACCESS_RIGHTS_USER_PAGE = 'RESET_ACCESS_RIGHTS_USER_PAGE';

// Access Rights One-off List
export const GET_ACCESS_RIGHTS_ONE_OFF_LIST_REQUEST = 'GET_ACCESS_RIGHTS_ONE_OFF_LIST_REQUEST';
export const GET_ACCESS_RIGHTS_ONE_OFF_LIST_SUCCESS = 'GET_ACCESS_RIGHTS_ONE_OFF_LIST_SUCCESS';
export const GET_ACCESS_RIGHTS_ONE_OFF_LIST_ERROR = 'GET_ACCESS_RIGHTS_ONE_OFF_LIST_ERROR';

export const GET_ACCESS_RIGHTS_ONE_OFF_BY_ID_REQUEST = 'GET_ACCESS_RIGHTS_ONE_OFF_BY_ID_REQUEST';
export const GET_ACCESS_RIGHTS_ONE_OFF_BY_ID_SUCCESS = 'GET_ACCESS_RIGHTS_ONE_OFF_BY_ID_SUCCESS';
export const GET_ACCESS_RIGHTS_ONE_OFF_BY_ID_ERROR = 'GET_ACCESS_RIGHTS_ONE_OFF_BY_ID_ERROR';

export const SUBMIT_ACCESS_RIGHTS_ONE_OFF_REQUEST = 'SUBMIT_ACCESS_RIGHTS_ONE_OFF_REQUEST';
export const SUBMIT_ACCESS_RIGHTS_ONE_OFF_SUCCESS = 'SUBMIT_ACCESS_RIGHTS_ONE_OFF_SUCCESS';
export const SUBMIT_ACCESS_RIGHTS_ONE_OFF_ERROR = 'SUBMIT_ACCESS_RIGHTS_ONE_OFF_ERROR';

export const DELETE_ACCESS_RIGHTS_ONE_OFF_BY_ID_REQUEST = 'DELETE_ACCESS_RIGHTS_ONE_OFF_BY_ID_REQUEST';
export const DELETE_ACCESS_RIGHTS_ONE_OFF_BY_ID_SUCCESS = 'DELETE_ACCESS_RIGHTS_ONE_OFF_BY_ID_SUCCESS';
export const DELETE_ACCESS_RIGHTS_ONE_OFF_BY_ID_ERROR = 'DELETE_ACCESS_RIGHTS_ONE_OFF_BY_ID_ERROR';

export const SUSPEND_LOCATION_ACCESS_RIGHTS_BY_ONE_OFF_REQUEST = 'SUSPEND_LOCATION_ACCESS_RIGHTS_BY_ONE_OFF_REQUEST';
export const SUSPEND_LOCATION_ACCESS_RIGHTS_BY_ONE_OFF_SUCCESS = 'SUSPEND_LOCATION_ACCESS_RIGHTS_BY_ONE_OFF_SUCCESS';
export const SUSPEND_LOCATION_ACCESS_RIGHTS_BY_ONE_OFF_ERROR = 'SUSPEND_LOCATION_ACCESS_RIGHTS_BY_ONE_OFF_ERROR';

export const REACTIVATE_LOCATION_ACCESS_RIGHTS_BY_ONE_OFF_REQUEST = 'REACTIVATE_LOCATION_ACCESS_RIGHTS_BY_ONE_OFF_REQUEST';
export const REACTIVATE_LOCATION_ACCESS_RIGHTS_BY_ONE_OFF_SUCCESS = 'REACTIVATE_LOCATION_ACCESS_RIGHTS_BY_ONE_OFF_SUCCESS';
export const REACTIVATE_LOCATION_ACCESS_RIGHTS_BY_ONE_OFF_ERROR = 'REACTIVATE_LOCATION_ACCESS_RIGHTS_BY_ONE_OFF_ERROR';

export const GET_USER_FROM_ACCESS_RIGHTS_ONE_OFF_REQUEST = 'GET_USER_FROM_ACCESS_RIGHTS_ONE_OFF_REQUEST';
export const GET_USER_FROM_ACCESS_RIGHTS_ONE_OFF_ERROR = 'GET_USER_FROM_ACCESS_RIGHTS_ONE_OFF_ERROR';
export const GET_USER_FROM_ACCESS_RIGHTS_ONE_OFF_SUCCESS = 'GET_USER_FROM_ACCESS_RIGHTS_ONE_OFF_SUCCESS';

export const RESET_ACCESS_RIGHTS_ONE_OFF_META = 'RESET_ACCESS_RIGHTS_ONE_OFF_DETAIL_META';
export const RESET_ACCESS_RIGHTS_ONE_OFF_PAGE = 'RESET_ACCESS_RIGHTS_ONE_OFF_DETAIL_PAGE';

// Door List
export const GET_DOOR_LIST_REQUEST = 'GET_DOOR_LIST_REQUEST';
export const GET_DOOR_LIST_SUCCESS = 'GET_DOOR_LIST_SUCCESS';
export const GET_DOOR_LIST_ERROR = 'GET_DOOR_LIST_ERROR';

export const SUBMIT_DOOR_REQUEST = 'SUBMIT_DOOR_REQUEST';
export const SUBMIT_DOOR_SUCCESS = 'SUBMIT_DOOR_SUCCESS';
export const SUBMIT_DOOR_ERROR = 'SUBMIT_DOOR_ERROR';

export const DELETE_DOOR_BY_ID_REQUEST = 'DELETE_DOOR_BY_ID_REQUEST';
export const DELETE_DOOR_BY_ID_SUCCESS = 'DELETE_DOOR_BY_ID_SUCCESS';
export const DELETE_DOOR_BY_ID_ERROR = 'DELETE_DOOR_BY_ID_ERROR';

export const GET_CONTROLLER_FROM_DOOR_REQUEST = 'GET_CONTROLLER_FROM_DOOR_REQUEST';
export const GET_CONTROLLER_FROM_DOOR_ERROR = 'GET_CONTROLLER_FROM_DOOR_ERROR';
export const GET_CONTROLLER_FROM_DOOR_SUCCESS = 'GET_CONTROLLER_FROM_DOOR_SUCCESS';

export const RESET_DOOR_META = 'RESET_DOOR_META';
export const RESET_DOOR_PAGE = 'RESET_DOOR_PAGE';

// Location List
export const GET_LOCATION_LIST_REQUEST = 'GET_LOCAITON_LIST_REQUEST';
export const GET_LOCATION_LIST_SUCCESS = 'GET_LOCAITON_LIST_SUCCESS';
export const GET_LOCATION_LIST_ERROR = 'GET_LOCAITON_LIST_ERROR';

export const RESET_LOCATION_LIST_META = 'RESET_LOCATION_LIST_META';
export const RESET_LOCATION_LIST_PAGE = 'RESET_LOCATION_LIST_PAGE';

// Location Detail Page
export const GET_LOCATION_BY_ID_REQUEST = 'GET_LOCATION_BY_ID_REQUEST';
export const GET_LOCATION_BY_ID_SUCCESS = 'GET_LOCATION_BY_ID_SUCCESS';
export const GET_LOCATION_BY_ID_ERROR = 'GET_LOCATION_BY_ID_ERROR';

export const SUBMIT_LOCATION_REQUEST = 'SUBMIT_LOCATION_REQUEST';
export const SUBMIT_LOCATION_SUCCESS = 'SUBMIT_LOCATION_SUCCESS';
export const SUBMIT_LOCATION_ERROR = 'SUBMIT_LOCATION_ERROR';

export const DELETE_LOCATION_BY_ID_REQUEST = 'DELETE_LOCATION_BY_ID_REQUEST';
export const DELETE_LOCATION_BY_ID_SUCCESS = 'DELETE_LOCATION_BY_ID_SUCCESS';
export const DELETE_LOCATION_BY_ID_ERROR = 'DELETE_LOCATION_BY_ID_ERROR';

export const SUSPEND_LOCATION_BY_ID_REQUEST = 'SUSPEND_LOCATION_BY_ID_REQUEST';
export const SUSPEND_LOCATION_BY_ID_SUCCESS = 'SUSPEND_LOCATION_BY_ID_SUCCESS';
export const SUSPEND_LOCATION_BY_ID_ERROR = 'SUSPEND_LOCATION_BY_ID_ERROR';

export const UNSUSPEND_LOCATION_BY_ID_REQUEST = 'UNSUSPEND_LOCATION_BY_ID_REQUEST';
export const UNSUSPEND_LOCATION_BY_ID_SUCCESS = 'UNSUSPEND_LOCATION_BY_ID_SUCCESS';
export const UNSUSPEND_LOCATION_BY_ID_ERROR = 'UNSUSPEND_LOCATION_BY_ID_ERROR';

export const GET_LOCATION_ENTITIES_REQUEST = 'GET_LOCATION_ENTITIES_REQUEST';
export const GET_LOCATION_ENTITIES_SUCCESS = 'GET_LOCATION_ENTITIES_SUCCESS';
export const GET_LOCATION_ENTITIES_ERROR = 'GET_LOCATION_ENTITIES_ERROR';

export const GET_LOCATION_DEPARTMENTS_REQUEST = 'GET_LOCATION_DEPARTMENTS_REQUEST';
export const GET_LOCATION_DEPARTMENTS_SUCCESS = 'GET_LOCATION_DEPARTMENTS_SUCCESS';
export const GET_LOCATION_DEPARTMENTS_ERROR = 'GET_LOCATION_DEPARTMENTS_ERROR';

export const RESET_LOCATION_DETAIL_META = 'RESET_LOCATION_DETAIL_META';
export const RESET_LOCATION_DETAIL_PAGE = 'RESET_LOCATION_DETAIL_PAGE';

// Location Access Rights by Group Page
export const GET_LOCATION_ACCESS_RIGHTS_BY_GROUP_REQUEST = 'GET_LOCATION_ACCESS_RIGHTS_BY_GROUP_REQUEST';
export const GET_LOCATION_ACCESS_RIGHTS_BY_GROUP_SUCCESS = 'GET_LOCATION_ACCESS_RIGHTS_BY_GROUP_SUCCESS';
export const GET_LOCATION_ACCESS_RIGHTS_BY_GROUP_ERROR = 'GET_LOCATION_ACCESS_RIGHTS_BY_GROUP_ERROR';

export const SUBMIT_LOCATION_ACCESS_RIGHTS_BY_GROUP_REQUEST = 'SUBMIT_LOCATION_ACCESS_RIGHTS_BY_GROUP_REQUEST';
export const SUBMIT_LOCATION_ACCESS_RIGHTS_BY_GROUP_SUCCESS = 'SUBMIT_LOCATION_ACCESS_RIGHTS_BY_GROUP_SUCCESS';
export const SUBMIT_LOCATION_ACCESS_RIGHTS_BY_GROUP_ERROR = 'SUBMIT_LOCATION_ACCESS_RIGHTS_BY_GROUP_ERROR';

export const SUSPEND_LOCATION_ACCESS_RIGHTS_BY_GROUP_REQUEST = 'SUSPEND_LOCATION_ACCESS_RIGHTS_BY_GROUP_REQUEST';
export const SUSPEND_LOCATION_ACCESS_RIGHTS_BY_GROUP_SUCCESS = 'SUSPEND_LOCATION_ACCESS_RIGHTS_BY_GROUP_SUCCESS';
export const SUSPEND_LOCATION_ACCESS_RIGHTS_BY_GROUP_ERROR = 'SUSPEND_LOCATION_ACCESS_RIGHTS_BY_GROUP_ERROR';

export const REACTIVATE_LOCATION_ACCESS_RIGHTS_BY_GROUP_REQUEST = 'REACTIVATE_LOCATION_ACCESS_RIGHTS_BY_GROUP_REQUEST';
export const REACTIVATE_LOCATION_ACCESS_RIGHTS_BY_GROUP_SUCCESS = 'REACTIVATE_LOCATION_ACCESS_RIGHTS_BY_GROUP_SUCCESS';
export const REACTIVATE_LOCATION_ACCESS_RIGHTS_BY_GROUP_ERROR = 'REACTIVATE_LOCATION_ACCESS_RIGHTS_BY_GROUP_ERROR';

export const DELETE_LOCATION_ACCESS_RIGHTS_BY_GROUP_REQUEST = 'DELETE_LOCATION_ACCESS_RIGHTS_BY_GROUP_REQUEST';
export const DELETE_LOCATION_ACCESS_RIGHTS_BY_GROUP_SUCCESS = 'DELETE_LOCATION_ACCESS_RIGHTS_BY_GROUP_SUCCESS';
export const DELETE_LOCATION_ACCESS_RIGHTS_BY_GROUP_ERROR = 'DELETE_LOCATION_ACCESS_RIGHTS_BY_GROUP_ERROR';

export const GET_LOCATION_ACCESS_RIGHTS_BY_GROUP_GROUPS_REQUEST = 'GET_LOCATION_ACCESS_RIGHTS_BY_GROUP_GROUPS_REQUEST';
export const GET_LOCATION_ACCESS_RIGHTS_BY_GROUP_GROUPS_SUCCESS = 'GET_LOCATION_ACCESS_RIGHTS_BY_GROUP_GROUPS_SUCCESS';
export const GET_LOCATION_ACCESS_RIGHTS_BY_GROUP_GROUPS_ERROR = 'GET_LOCATION_ACCESS_RIGHTS_BY_GROUP_GROUPS_ERROR';


export const RESET_LOCATION_ACCESS_RIGHTS_BY_GROUP_META = 'RESET_LOCATION_ACCESS_RIGHTS_BY_GROUP_META';
export const RESET_LOCATION_ACCESS_RIGHTS_BY_GROUP_PAGE = 'RESET_LOCATION_ACCESS_RIGHTS_BY_GROUP_PAGE';

// Entity Access Rights By Group Page
export const GET_ENTITY_ACCESS_RIGHTS_BY_GROUP_REQUEST = 'GET_ENTITY_ACCESS_RIGHTS_BY_GROUP_REQUEST';
export const GET_ENTITY_ACCESS_RIGHTS_BY_GROUP_SUCCESS = 'GET_ENTITY_ACCESS_RIGHTS_BY_GROUP_SUCCESS';
export const GET_ENTITY_ACCESS_RIGHTS_BY_GROUP_ERROR = 'GET_ENTITY_ACCESS_RIGHTS_BY_GROUP_ERROR';

export const SUBMIT_ENTITY_ACCESS_RIGHTS_BY_GROUP_REQUEST = 'SUBMIT_ENTITY_ACCESS_RIGHTS_BY_GROUP_REQUEST';
export const SUBMIT_ENTITY_ACCESS_RIGHTS_BY_GROUP_SUCCESS = 'SUBMIT_ENTITY_ACCESS_RIGHTS_BY_GROUP_SUCCESS';
export const SUBMIT_ENTITY_ACCESS_RIGHTS_BY_GROUP_ERROR = 'SUBMIT_ENTITY_ACCESS_RIGHTS_BY_GROUP_ERROR';

export const DELETE_ENTITY_ACCESS_RIGHTS_BY_GROUP_REQUEST = 'DELETE_ENTITY_ACCESS_RIGHTS_BY_GROUP_REQUEST';
export const DELETE_ENTITY_ACCESS_RIGHTS_BY_GROUP_SUCCESS = 'DELETE_ENTITY_ACCESS_RIGHTS_BY_GROUP_SUCCESS';
export const DELETE_ENTITY_ACCESS_RIGHTS_BY_GROUP_ERROR = 'DELETE_ENTITY_ACCESS_RIGHTS_BY_GROUP_ERROR';

export const RESET_ENTITY_ACCESS_RIGHTS_BY_GROUP_META = 'RESET_ENTITY_ACCESS_RIGHTS_BY_GROUP_META';
export const RESET_ENTITY_ACCESS_RIGHTS_BY_GROUP_PAGE = 'RESET_ENTITY_ACCESS_RIGHTS_BY_GROUP_PAGE';

// Emergency List Page
export const GET_EMERGENCY_LIST_REQUEST = 'GET_EMERGENCY_LIST_REQUEST';
export const GET_EMERGENCY_LIST_SUCCESS = 'GET_EMERGENCY_LIST_SUCCESS';
export const GET_EMERGENCY_LIST_ERROR = 'GET_EMERGENCY_LIST_ERROR';

export const RESET_EMERGENCY_LIST_META = 'RESET_EMERGENCY_LIST_META';
export const RESET_EMERGENCY_LIST_PAGE = 'RESET_EMERGENCY_LIST_PAGE';

// Emergency Detail Page
export const GET_EMERGENCY_BY_ID_REQUEST = 'GET_EMERGENCY_BY_ID_REQUEST';
export const GET_EMERGENCY_BY_ID_SUCCESS = 'GET_EMERGENCY_BY_ID_SUCCESS';
export const GET_EMERGENCY_BY_ID_ERROR = 'GET_EMERGENCY_BY_ID_ERROR';

export const SUBMIT_EMERGENCY_REQUEST = 'SUBMIT_EMERGENCY_REQUEST';
export const SUBMIT_EMERGENCY_SUCCESS = 'SUBMIT_EMERGENCY_SUCCESS';
export const SUBMIT_EMERGENCY_ERROR = 'SUBMIT_EMERGENCY_ERROR';

export const DELETE_EMERGENCY_BY_ID_REQUEST = 'DELETE_EMERGENCY_BY_ID_REQUEST';
export const DELETE_EMERGENCY_BY_ID_SUCCESS = 'DELETE_EMERGENCY_BY_ID_SUCCESS';
export const DELETE_EMERGENCY_BY_ID_ERROR = 'DELETE_EMERGENCY_BY_ID_ERROR';

export const SUSPEND_EMERGENCY_BY_ID_REQUEST = 'SUSPEND_EMERGENCY_BY_ID_REQUEST';
export const SUSPEND_EMERGENCY_BY_ID_SUCCESS = 'SUSPEND_EMERGENCY_BY_ID_SUCCESS';
export const SUSPEND_EMERGENCY_BY_ID_ERROR = 'SUSPEND_EMERGENCY_BY_ID_ERROR';

export const UNSUSPEND_EMERGENCY_BY_ID_REQUEST = 'UNSUSPEND_EMERGENCY_BY_ID_REQUEST';
export const UNSUSPEND_EMERGENCY_BY_ID_SUCCESS = 'UNSUSPEND_EMERGENCY_BY_ID_SUCCESS';
export const UNSUSPEND_EMERGENCY_BY_ID_ERROR = 'UNSUSPEND_EMERGENCY_BY_ID_ERROR';

export const RESET_EMERGENCY_DETAIL_META = 'RESET_EMERGENCY_DETAIL_META';
export const RESET_EMERGENCY_DETAIL_PAGE = 'RESET_EMERGENCY_DETAIL_PAGE';

export const GET_EMERGENCY_LOCATION_LIST_REQUEST = 'GET_EMERGENCY_LOCATION_LIST_REQUEST';
export const GET_EMERGENCY_LOCATION_LIST_SUCCESS = 'GET_EMERGENCY_LOCATION_LIST_SUCCESS';
export const GET_EMERGENCY_LOCATION_LIST_ERROR = 'GET_EMERGENCY_LOCATION_LIST_ERROR';

export const GET_EMERGENCY_DOOR_LIST_REQUEST = 'GET_EMERGENCY_DOOR_LIST_REQUEST';
export const GET_EMERGENCY_DOOR_LIST_SUCCESS = 'GET_EMERGENCY_DOOR_LIST_SUCCESS';
export const GET_EMERGENCY_DOOR_LIST_ERROR = 'GET_EMERGENCY_DOOR_LIST_ERROR';


// Entity Users Tab
export const GET_USER_ENTITY_MAPPINGS_BY_ENTITY_ID_REQUEST = 'GET_USER_ENTITY_MAPPINGS_BY_ENTITY_ID_REQUEST';
export const GET_USER_ENTITY_MAPPINGS_BY_ENTITY_ID_SUCCESS = 'GET_USER_ENTITY_MAPPINGS_BY_ENTITY_ID_SUCCESS';
export const GET_USER_ENTITY_MAPPINGS_BY_ENTITY_ID_ERROR = 'GET_USER_ENTITY_MAPPINGS_BY_ENTITY_ID_ERROR';

export const CREATE_USER_ENTITY_MAPPING_REQUEST = 'CREATE_USER_ENTITY_MAPPING_REQUEST';
export const CREATE_USER_ENTITY_MAPPING_SUCCESS = 'CREATE_USER_ENTITY_MAPPING_SUCCESS';
export const CREATE_USER_ENTITY_MAPPING_ERROR = 'CREATE_USER_ENTITY_MAPPING_ERROR';

export const DELETE_USER_ENTITY_MAPPING_BY_ID_REQUEST = 'DELETE_USER_ENTITY_MAPPING_BY_ID_REQUEST';
export const DELETE_USER_ENTITY_MAPPING_BY_ID_SUCCESS = 'DELETE_USER_ENTITY_MAPPING_BY_ID_SUCCESS';
export const DELETE_USER_ENTITY_MAPPING_BY_ID_ERROR = 'DELETE_USER_ENTITY_MAPPING_BY_ID_ERROR';

export const RESET_ENTITY_USER_META = 'RESET_ENTITY_USER_META';
export const RESET_ENTITY_USER_PAGE = 'RESET_ENTITY_USER_PAGE';

// Alerts List Page
export const GET_ALERTS_BY_DEPARTMENT_ID_REQUEST = 'GET_ALERTS_BY_DEPARTMENT_ID_REQUEST';
export const GET_ALERTS_BY_DEPARTMENT_ID_SUCCESS = 'GET_ALERTS_BY_DEPARTMENT_ID_SUCCESS';
export const GET_ALERTS_BY_DEPARTMENT_ID_ERROR = 'GET_ALERTS_BY_DEPARTMENT_ID_ERROR';


export const GET_DOORS_IN_ALERTS_REQUEST = 'GET_DOORS_IN_ALERTS_REQUEST';
export const GET_DOORS_IN_ALERTS_ERROR = 'GET_DOORS_IN_ALERTS_ERROR';
export const GET_DOORS_IN_ALERTS_SUCCESS = 'GET_DOORS_IN_ALERTS_SUCCESS';

export const GET_LOCATIONS_IN_ALERTS_REQUEST = 'GET_LOCATIONS_IN_ALERTS_REQUEST';
export const GET_LOCATIONS_IN_ALERTS_ERROR = 'GET_LOCATIONS_IN_ALERTS_ERROR';
export const GET_LOCATIONS_IN_ALERTS_SUCCESS = 'GET_LOCATIONS_IN_ALERTS_SUCCESS';

export const RESET_ALERT_LIST_META = 'RESET_ALERT_LIST_META';
export const RESET_ALERT_LIST_PAGE = 'RESET_ALERT_LIST_PAGE';

// Alert Detail Page
export const GET_ALERT_BY_ID_REQUEST = 'GET_ALERT_BY_ID_REQUEST';
export const GET_ALERT_BY_ID_SUCCESS = 'GET_ALERT_BY_ID_SUCCESS';
export const GET_ALERT_BY_ID_ERROR = 'GET_ALERT_BY_ID_ERROR';

export const ACKNOWLEDGE_ALERT_BY_ID_REQUEST = 'ACKNOWLEDGE_ALERT_BY_ID_REQUEST';
export const ACKNOWLEDGE_ALERT_BY_ID_SUCCESS = 'ACKNOWLEDGE_ALERT_BY_ID_SUCCESS';
export const ACKNOWLEDGE_ALERT_BY_ID_ERROR = 'ACKNOWLEDGE_ALERT_BY_ID_ERROR';

export const RESET_ALERT_DETAIL_META = 'RESET_ALERT_DETAIL_META';
export const RESET_ALERT_DETAIL_PAGE = 'RESET_ALERT_DETAIL_PAGE';


// Dashboard Page
export const GET_DASHBOARD_DETAIL_REQUEST = 'GET_DASHBOARD_DETAIL_REQUEST';
export const GET_DASHBOARD_DETAIL_SUCCESS = 'GET_DASHBOARD_DETAIL_SUCCESS';
export const GET_DASHBOARD_DETAIL_ERROR = 'GET_DASHBOARD_DETAIL_ERROR';

export const RESET_DASHBOARD_META = 'RESET_DASHBOARD_META';
export const RESET_DASHBOARD_PAGE = 'RESET_DASHBOARD_PAGE';

// Group List Page
export const GET_GROUP_LIST_REQUEST = 'GET_GROUP_LIST_REQUEST';
export const GET_GROUP_LIST_SUCCESS = 'GET_GROUP_LIST_SUCCESS';
export const GET_GROUP_LIST_ERROR = 'GET_GROUP_LIST_ERROR';

export const RESET_GROUP_LIST_META = 'RESET_GROUP_LIST_META';
export const RESET_GROUP_LIST_PAGE = 'RESET_GROUP_LIST_PAGE';

// Group Detail Page
export const GET_GROUP_BY_ID_REQUEST = 'GET_GROUP_BY_ID_REQUEST';
export const GET_GROUP_BY_ID_SUCCESS = 'GET_GROUP_BY_ID_SUCCESS';
export const GET_GROUP_BY_ID_ERROR = 'GET_GROUP_BY_ID_ERROR';

export const SUBMIT_GROUP_REQUEST = 'SUBMIT_GROUP_REQUEST';
export const SUBMIT_GROUP_SUCCESS = 'SUBMIT_GROUP_SUCCESS';
export const SUBMIT_GROUP_ERROR = 'SUBMIT_GROUP_ERROR';

export const SUSPEND_GROUP_BY_ID_REQUEST = 'SUSPEND_GROUP_BY_ID_REQUEST';
export const SUSPEND_GROUP_BY_ID_SUCCESS = 'SUSPEND_GROUP_BY_ID_SUCCESS';
export const SUSPEND_GROUP_BY_ID_ERROR = 'SUSPEND_GROUP_BY_ID_ERROR';

export const UNSUSPEND_GROUP_BY_ID_REQUEST = 'UNSUSPEND_GROUP_BY_ID_REQUEST';
export const UNSUSPEND_GROUP_BY_ID_SUCCESS = 'UNSUSPEND_GROUP_BY_ID_SUCCESS';
export const UNSUSPEND_GROUP_BY_ID_ERROR = 'UNSUSPEND_GROUP_BY_ID_ERROR';

export const RESET_GROUP_DETAIL_META = 'RESET_GROUP_DETAIL_META';
export const RESET_GROUP_DETAIL_PAGE = 'RESET_GROUP_DETAIL_PAGE';

export const GET_GROUP_MEMBER_LIST_REQUEST = 'GET_GROUP_MEMBER_LIST_REQUEST';
export const GET_GROUP_MEMBER_LIST_ERROR = 'GET_GROUP_MEMBER_LIST_ERROR';
export const GET_GROUP_MEMBER_LIST_SUCCESS = 'GET_GROUP_MEMBER_LIST_SUCCESS';

// Events List
export const GET_EVENTS_LIST_REQUEST = 'GET_EVENTS_LIST_REQUEST';
export const GET_EVENTS_LIST_SUCCESS = 'GET_EVENTS_LIST_SUCCESS';
export const GET_EVENTS_LIST_ERROR = 'GET_EVENTS_LIST_ERROR';

// Admin Roles

export const GET_ADMIN_ROLES_LIST_REQUEST = 'GET_ADMIN_ROLES_LIST_REQUEST';
export const GET_ADMIN_ROLES_LIST_SUCCESS = 'GET_ADMIN_ROLES_LIST_SUCCESS';
export const GET_ADMIN_ROLES_LIST_ERROR = 'GET_ADMIN_ROLES_LIST_ERROR';

export const GET_ADMIN_ROLES_BY_ID_REQUEST = 'GET_ADMIN_ROLES_BY_ID_REQUEST';
export const GET_ADMIN_ROLES_BY_ID_SUCCESS = 'GET_ADMIN_ROLES_BY_ID_SUCCESS';
export const GET_ADMIN_ROLES_BY_ID_ERROR = 'GET_ADMIN_ROLES_BY_ID_ERROR';

export const SUBMIT_ADMIN_ROLES_REQUEST = 'SUBMIT_ADMIN_ROLES_REQUEST';
export const SUBMIT_ADMIN_ROLES_SUCCESS = 'SUBMIT_ADMIN_ROLES_SUCCESS';
export const SUBMIT_ADMIN_ROLES_ERROR = 'SUBMIT_ADMIN_ROLES_ERROR';

export const UNSUSPEND_ADMIN_ROLES_BY_ID_REQUEST = 'UNSUSPEND_ADMIN_ROLES_BY_ID_REQUEST';
export const UNSUSPEND_ADMIN_ROLES_BY_ID_SUCCESS = 'UNSUSPEND_ADMIN_ROLES_BY_ID_SUCCESS';
export const UNSUSPEND_ADMIN_ROLES_BY_ID_ERROR = 'UNSUSPEND_ADMIN_ROLES_BY_ID_ERROR';

export const SUSPEND_ADMIN_ROLES_BY_ID_REQUEST = 'SUSPEND_ADMIN_ROLES_BY_ID_REQUEST';
export const SUSPEND_ADMIN_ROLES_BY_ID_SUCCESS = 'SUSPEND_ADMIN_ROLES_BY_ID_SUCCESS';
export const SUSPEND_ADMIN_ROLES_BY_ID_ERROR = 'SUSPEND_ADMIN_ROLES_BY_ID_ERROR';

export const GET_DEPARTMENTS_FROM_ADMIN_ROLES_REQUEST = 'GET_DEPARTMENTS_FROM_ADMIN_ROLES_REQUEST';
export const GET_DEPARTMENTS_FROM_ADMIN_ROLES_ERROR = 'GET_DEPARTMENTS_FROM_ADMIN_ROLES_ERROR';
export const GET_DEPARTMENTS_FROM_ADMIN_ROLES_SUCCESS = 'GET_DEPARTMENTS_FROM_ADMIN_ROLES_SUCCESS';

export const RESET_ADMIN_ROLES_DETAIL_META = 'RESET_ADMIN_ROLES_DETAIL_META';
export const RESET_ADMIN_ROLES_DETAIL_PAGE = 'RESET_ADMIN_ROLES_DETAIL_PAGE';
// System Message List Page
export const GET_SYSTEM_MESSAGE_LIST_REQUEST = 'GET_SYSTEM_MESSAGE_LIST_REQUEST';
export const GET_SYSTEM_MESSAGE_LIST_SUCCESS = 'GET_SYSTEM_MESSAGE_LIST_SUCCESS';
export const GET_SYSTEM_MESSAGE_LIST_ERROR = 'GET_SYSTEM_MESSAGE_LIST_ERROR';

export const RESET_SYSTEM_MESSAGE_LIST_META = 'RESET_SYSTEM_MESSAGE_LIST_META';
export const RESET_SYSTEM_MESSAGE_LIST_PAGE = 'RESET_SYSTEM_MESSAGE_LIST_PAGE';

// System Message Detail Page
export const GET_SYSTEM_MESSAGE_BY_ID_REQUEST = 'GET_SYSTEM_MESSAGE_BY_ID_REQUEST';
export const GET_SYSTEM_MESSAGE_BY_ID_SUCCESS = 'GET_SYSTEM_MESSAGE_BY_ID_SUCCESS';
export const GET_SYSTEM_MESSAGE_BY_ID_ERROR = 'GET_SYSTEM_MESSAGE_BY_ID_ERROR';

export const SUBMIT_SYSTEM_MESSAGE_REQUEST = 'SUBMIT_SYSTEM_MESSAGE_REQUEST';
export const SUBMIT_SYSTEM_MESSAGE_SUCCESS = 'SUBMIT_SYSTEM_MESSAGE_SUCCESS';
export const SUBMIT_SYSTEM_MESSAGE_ERROR = 'SUBMIT_SYSTEM_MESSAGE_ERROR';

export const GET_SYSTEM_MESSAGE_LOCATIONS_REQUEST = 'GET_SYSTEM_MESSAGE_LOCATIONS_REQUEST';
export const GET_SYSTEM_MESSAGE_LOCATIONS_SUCCESS = 'GET_SYSTEM_MESSAGE_LOCATIONS_SUCCESS';
export const GET_SYSTEM_MESSAGE_LOCATIONS_ERROR = 'GET_SYSTEM_MESSAGE_LOCATIONS_ERROR';

export const GET_SYSTEM_MESSAGE_DOORS_REQUEST = 'GET_SYSTEM_MESSAGE_DOORS_REQUEST';
export const GET_SYSTEM_MESSAGE_DOORS_SUCCESS = 'GET_SYSTEM_MESSAGE_DOORS_SUCCESS';
export const GET_SYSTEM_MESSAGE_DOORS_ERROR = 'GET_SYSTEM_MESSAGE_DOORS_ERROR';

export const RESET_SYSTEM_MESSAGE_DETAIL_META = 'RESET_SYSTEM_MESSAGE_DETAIL_META';
export const RESET_SYSTEM_MESSAGE_DETAIL_PAGE = 'RESET_SYSTEM_MESSAGE_DETAIL_PAGE';

// Location Admin Page
export const GET_ADMIN_ROLES_BY_LOCATION_REQUEST = 'GET_ADMIN_ROLES_BY_LOCATION_REQUEST';
export const GET_ADMIN_ROLES_BY_LOCATION_SUCCESS = 'GET_ADMIN_ROLES_BY_LOCATION_SUCCESS';
export const GET_ADMIN_ROLES_BY_LOCATION_ERROR = 'GET_ADMIN_ROLES_BY_LOCATION_ERROR';

export const SUBMIT_ADMIN_ROLES_BY_LOCATION_REQUEST = 'SUBMIT_ADMIN_ROLES_BY_LOCATION_REQUEST';
export const SUBMIT_ADMIN_ROLES_BY_LOCATION_SUCCESS = 'SUBMIT_ADMIN_ROLES_BY_LOCATION_SUCCESS';
export const SUBMIT_ADMIN_ROLES_BY_LOCATION_ERROR = 'SUBMIT_ADMIN_ROLES_BY_LOCATION_ERROR';

export const SUSPEND_LOCATION_ADMIN_REQUEST = 'SUSPEND_LOCATION_ADMIN_REQUEST';
export const SUSPEND_LOCATION_ADMIN_SUCCESS = 'SUSPEND_LOCATION_ADMIN_SUCCESS';
export const SUSPEND_LOCATION_ADMIN_ERROR = 'SUSPEND_LOCATION_ADMIN_ERROR';
export const REACTIVATE_LOCATION_ADMIN_REQUEST = 'REACTIVATE_LOCATION_ADMIN_REQUEST';
export const REACTIVATE_LOCATION_ADMIN_SUCCESS = 'REACTIVATE_LOCATION_ADMIN_SUCCESS';
export const REACTIVATE_LOCATION_ADMIN_ERROR = 'REACTIVATE_LOCATION_ADMIN_ERROR';

export const RESET_LOCATION_ADMIN_ROLE_META = 'RESET_LOCATION_ADMIN_ROLE_META';
export const RESET_LOCATION_ADMIN_ROLE_PAGE = 'RESET_LOCATION_ADMIN_ROLE_PAGE';

// Status List Page
export const GET_STATUS_LIST_REQUEST = 'GET_STATUS_LIST_REQUEST';
export const GET_STATUS_LIST_SUCCESS = 'GET_STATUS_LIST_SUCCESS';
export const GET_STATUS_LIST_ERROR = 'GET_STATUS_LIST_ERROR';

export const GET_CONTROLLER_STATUS_LIST_REQUEST = 'GET_CONTROLLER_STATUS_LIST_REQUEST';
export const GET_CONTROLLER_STATUS_LIST_SUCCESS = 'GET_CONTROLLER_STATUS_LIST_SUCCESS';
export const GET_CONTROLLER_STATUS_LIST_ERROR = 'GET_CONTROLLER_STATUS_LIST_ERROR';

export const RESET_STATUS_LIST_META = 'RESET_STATUS_LIST_META';
export const RESET_STATUS_LIST_PAGE = 'RESET_STATUS_LIST_PAGE';

// Calls List Page
export const GET_CALLS_LIST_REQUEST = 'GET_CALLS_LIST_REQUEST';
export const GET_CALLS_LIST_SUCCESS = 'GET_CALLS_LIST_SUCCESS';
export const GET_CALLS_LIST_ERROR = 'GET_CALLS_LIST_ERROR';

export const RESET_CALLS_LIST_META = 'RESET_CALLS_LIST_META';
export const RESET_CALLS_LIST_PAGE = 'RESET_CALLS_LIST_PAGE';

// Agent List
export const GET_AGENT_LIST_REQUEST = 'GET_AGENT_LIST_REQUEST';
export const GET_AGENT_LIST_SUCCESS = 'GET_AGENT_LIST_SUCCESS';
export const GET_AGENT_LIST_ERROR = 'GET_AGENT_LIST_ERROR';

export const RESET_AGENT_LIST_META = 'RESET_AGENT_LIST_META';
export const RESET_AGENT_LIST_PAGE = 'RESET_AGENT_LIST_PAGE';

// Agent Detail Page
export const GET_AGENT_BY_ID_REQUEST = 'GET_AGENT_BY_ID_REQUEST';
export const GET_AGENT_BY_ID_SUCCESS = 'GET_AGENT_BY_ID_SUCCESS';
export const GET_AGENT_BY_ID_ERROR = 'GET_AGENT_BY_ID_ERROR';

export const SUBMIT_AGENT_REQUEST = 'SUBMIT_AGENT_REQUEST';
export const SUBMIT_AGENT_SUCCESS = 'SUBMIT_AGENT_SUCCESS';
export const SUBMIT_AGENT_ERROR = 'SUBMIT_AGENT_ERROR';

export const SUSPEND_AGENT_BY_ID_REQUEST = 'SUSPEND_AGENT_BY_ID_REQUEST';
export const SUSPEND_AGENT_BY_ID_SUCCESS = 'SUSPEND_AGENT_BY_ID_SUCCESS';
export const SUSPEND_AGENT_BY_ID_ERROR = 'SUSPEND_AGENT_BY_ID_ERROR';

export const UNSUSPEND_AGENT_BY_ID_REQUEST = 'UNSUSPEND_AGENT_BY_ID_REQUEST';
export const UNSUSPEND_AGENT_BY_ID_SUCCESS = 'UNSUSPEND_AGENT_BY_ID_SUCCESS';
export const UNSUSPEND_AGENT_BY_ID_ERROR = 'UNSUSPEND_AGENT_BY_ID_ERROR';

export const UPDATE_AGENT_PASSWORD_REQUEST = 'UPDATE_AGENT_PASSWORD_REQUEST';
export const UPDATE_AGENT_PASSWORD_SUCCESS = 'UPDATE_AGENT_PASSWORD_SUCCESS';
export const UPDATE_AGENT_PASSWORD_ERROR = 'UPDATE_AGENT_PASSWORD_ERROR';

export const RESET_AGENT_DETAIL_META = 'RESET_AGENT_DETAIL_META';
export const RESET_AGENT_DETAIL_PAGE = 'RESET_AGENT_DETAIL_PAGE';

export const GET_DOORS_FOR_AGENT_REQUEST = 'GET_DOORS_FOR_AGENT_REQUEST';
export const GET_DOORS_FOR_AGENT_SUCCESS = 'GET_DOORS_FOR_AGENT_SUCCESS';
export const GET_DOORS_FOR_AGENT_ERROR = 'GET_DOORS_FOR_AGENT_ERROR';

// External QR code
export const GET_EXTERNAL_USER_BY_ID_REQUEST = 'GET_EXTERNAL_USER_BY_ID_REQUEST';
export const GET_EXTERNAL_USER_BY_ID_ERROR = 'GET_EXTERNAL_USER_BY_ID_ERROR';
export const GET_EXTERNAL_USER_BY_ID_SUCCESS = 'GET_EXTERNAL_USER_BY_ID_SUCCESS';
export const RESET_EXTERNAL_USER_PAGE = 'RESET_EXTERNAL_USER_PAGE';

// Emergency Report
export const GET_EMERGENCY_REPORT_LIST_REQUEST = 'GET_EMERGENCY_REPORT_LIST_REQUEST';
export const GET_EMERGENCY_REPORT_LIST_SUCCESS = 'GET_EMERGENCY_REPORT_LIST_SUCCESS';
export const GET_EMERGENCY_REPORT_LIST_ERROR = 'GET_EMERGENCY_REPORT_LIST_ERROR';

//Controller Report
export const GET_CONTROLLER_REPORT_LIST_REQUEST = 'GET_CONTROLLER_REPORT_LIST_REQUEST';
export const GET_CONTROLLER_REPORT_LIST_SUCCESS = 'GET_CONTROLLER_REPORT_LIST_SUCCESS';
export const GET_CONTROLLER_REPORT_LIST_ERROR = 'GET_CONTROLLER_REPORT_LIST_ERROR';

// People Count
export const GET_PEOPLE_COUNT_LIST_REQUEST = 'GET_PEOPLE_COUNT_REQUEST';
export const GET_PEOPLE_COUNT_LIST_ERROR = 'GET_PEOPLE_COUNT_ERROR';
export const GET_PEOPLE_COUNT_LIST_SUCCESS = 'GET_PEOPLE_COUNT_SUCCESS';

// Security Features

export const GET_SECURITY_FEATURES_LIST_REQUEST = 'GET_SECURITY_FEATURES_LIST_REQUEST';
export const GET_SECURITY_FEATURES_LIST_SUCCESS = 'GET_SECURITY_FEATURES_LIST_SUCCESS';
export const GET_SECURITY_FEATURES_LIST_ERROR = 'GET_SECURITY_FEATURES_LIST_ERROR';

export const GET_CUSTOM_AUTH_BY_SECURITY_FEATURES_SUCCESS = 'GET_CUSTOM_AUTH_BY_SECURITY_FEATURES_SUCCESS';
export const GET_CUSTOM_AUTH_BY_SECURITY_FEATURES_ERROR = 'GET_CUSTOM_AUTH_BY_SECURITY_FEATURES_ERROR';
export const GET_CUSTOM_AUTH_BY_SECURITY_FEATURES_REQUEST = 'GET_CUSTOM_AUTH_BY_SECURITY_FEATURES_REQUEST';

export const GET_SECURITY_FEATURES_BY_ID_REQUEST = 'GET_SECURITY_FEATURES_BY_ID_REQUEST';
export const GET_SECURITY_FEATURES_BY_ID_SUCCESS = 'GET_SECURITY_FEATURES_BY_ID_SUCCESS';
export const GET_SECURITY_FEATURES_BY_ID_ERROR = 'GET_SECURITY_FEATURES_BY_ID_ERROR';

export const SUBMIT_SECURITY_FEATURES_REQUEST = 'SUBMIT_SECURITY_FEATURES_REQUEST';
export const SUBMIT_SECURITY_FEATURES_SUCCESS = 'SUBMIT_SECURITY_FEATURES_SUCCESS';
export const SUBMIT_SECURITY_FEATURES_ERROR = 'SUBMIT_SECURITY_FEATURES_ERROR';

export const RESET_SECURITY_FEATURES_DETAIL_META = 'RESET_SECURITY_FEATURES_DETAIL_META';
export const RESET_SECURITY_FEATURES_DETAIL_PAGE = 'RESET_SECURITY_FEATURES_DETAIL_PAGE';

export const DELETE_SECURITY_FEATURE_BY_ID_REQUEST = 'DELETE_SECURITY_FEATURE_BY_ID_REQUEST';
export const DELETE_SECURITY_FEATURE_BY_ID_SUCCESS = 'DELETE_SECURITY_FEATURE_BY_ID_SUCCESS';
export const DELETE_SECURITY_FEATURE_BY_ID_ERROR = 'DELETE_SECURITY_FEATURE_BY_ID_ERROR';

// REPORT LIST PAGE
export const GET_REPORT_LIST_REQUEST = 'GET_REPORT_LIST_REQUEST';
export const GET_REPORT_LIST_ERROR = 'GET_REPORT_LIST_ERROR';
export const GET_REPORT_LIST_SUCCESS = 'GET_REPORT_LIST_SUCCESS';

export const RESET_REPORT_LIST_META = 'RESET_REPORT_LIST_META';
export const RESET_REPORT_LIST_DETAIL_PAGE = 'RESET_REPORT_DETAIL_PAGE';
export const RESET_REPORT_LIST_PAGE = 'RESET_REPORT_LIST_PAGE';

export const DOWNLOAD_CONTROLLER_REPORTS_REQUEST = 'DOWNLOAD_CONTROLLER_REPORTS_REQUEST';
export const DOWNLOAD_CONTROLLER_REPORTS_ERROR = 'DOWNLOAD_CONTROLLER_REPORTS_ERROR';
export const DOWNLOAD_CONTROLLER_REPORTS_SUCCESS = 'DOWNLOAD_CONTROLLER_REPORTS_SUCCESS';

export const RESET_DOWNLOAD_REPORTS_META = 'RESET_DOWNLOAD_REPORTS_META';
export const RESET_DOWNLOAD_REPORTS_PAGE = 'RESET_DOWNLOAD_REPORTS_PAGE';

//Location Report Page
export const GET_LOCATION_REPORT_REQUEST = 'GET_LOCATION_REPORT_REQUEST';
export const GET_LOCATION_REPORT_ERROR = 'GET_LOCATION_REPORT_ERROR';
export const GET_LOCATION_REPORT_SUCCESS = 'GET_LOCATION_REPORT_SUCCESS';

export const RESET_LOCATION_REPORT_META = 'RESET_LOCATION_REPORT_META';
export const RESET_LOCATION_REPORT_PAGE = 'RESET_LOCATION_REPORT_PAGE';

export const DOWNLOAD_LOCATION_REPORTS_REQUEST = 'DOWNLOAD_LOCATION_REPORTS_REQUEST';
export const DOWNLOAD_LOCATION_REPORTS_ERROR = 'DOWNLOAD_LOCATION_REPORTS_ERROR';
export const DOWNLOAD_LOCATION_REPORTS_SUCCESS = 'DOWNLOAD_LOCATION_REPORTS_SUCCESS';

export const RESET_DOWNLOAD_LOCATION_REPORTS_META = 'RESET_DOWNLOAD_LOCATION_REPORTS_META';
export const RESET_DOWNLOAD_LOCATION_REPORTS_PAGE = 'RESET_DOWNLOAD_LOCATION_REPORTS_PAGE';